name: Main
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Pause for 5 seconds
              run: |
                  sleep 5
